### ISSUE TITLE
rails 5 rc throws and error

### ISSUE THREAD

**Issue by atussec** [thredded/thredded#288]
am using rails 5rc1 and install threded on it. when i open a topic i get this error
`ArgumentError in Thredded::TopicsController#show
`
on this line 
` # fix for Rails 3.0
      def find_last
        if !loaded? and offset_value || limit_value
          @last ||= to_a.last
        else`
how can i fix this?

**Comment by atussec** [comment]
for anyone who face this issue, i fixed it by upgrading to latest version of will_paginate

**Comment by jayroh** [comment]
Similarly with kaminari - rails5 support is still hanging out in the master branch over there. 

See the gemfile we use to deploy to Heroku here - https://github.com/thredded/thredded/blob/master/heroku.gemfile - it has some good info regarding what you currently have to do to get everything to "just work" with Rails 5 rc1
